version: '3'
services:
  cache:
    image: redis
    command: redis-server  --requirepass "password" 
    ports:
      - "6379:6379"
    
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: stdlib
    
    